protected/models/Inbox.php
<?php

/**
 * This is the model class for table "inbox".
 *
 * The followings are the available columns in table 'inbox':
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $message
 * @property integer $is_read
 * @property integer $is_publish
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $update_user_id
 */
class Inbox extends CActiveRecord
{
	public $captcha;
	
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'inbox';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, email, message, captcha', 'required'),
			array('is_read, captcha, is_publish, create_user_id, update_user_id', 'numerical', 'integerOnly'=>true),
			array('name, subjek, phone', 'length', 'max'=>255),
			array('email', 'email'),
			array('create_time, update_time', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, email, subjek, phone, message, is_read, is_publish, create_time, update_time, create_user_id, update_user_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'From',
			'subjek' => 'Subjek',
			'captcha'=>'Verification Code',
			'email' => 'Email',
			'phone' => 'Phone',
			'message' => 'Message',
			'is_read' => 'Status',
			'is_publish' => 'Publish',
			'create_time' => 'Create Time',
			'update_time' => 'Update Time',
			'create_user_id' => 'Create User',
			'update_user_id' => 'Update User',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('phone',$this->phone,true);
		$criteria->compare('subjek',$this->subjek,true);
		$criteria->compare('message',$this->message,true);
		$criteria->compare('is_read',$this->is_read);
		$criteria->compare('is_publish',$this->is_publish);
		$criteria->compare('create_time',$this->create_time,true);
		$criteria->compare('update_time',$this->update_time,true);
		$criteria->compare('create_user_id',$this->create_user_id);
		$criteria->compare('update_user_id',$this->update_user_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Inbox the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function beforeSave() {
	
		if ($this->isNewRecord){
			$this->create_time = new CDbExpression('NOW()');
			$this->create_user_id = Yii::app()->user->id;
		}else{
			$this->update_time = new CDbExpression('NOW()');
			$this->update_user_id = Yii::app()->user->id;
		}	
		return parent::beforeSave();
	}

}

protected/controllers/InboxController.php
<?php

class InboxController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/administrator/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view'),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('create','update'),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete'),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionView($id)
    {
        $model = $this->loadModel($id);
        
        if($model->is_read == 0)
        {          
                $model->is_read = 1;
                $model->update();
        }
        
        $this->render('view',array(
        'model'=>$model,
        ));
    }

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Inbox;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Inbox']))
{
$model->attributes=$_POST['Inbox'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Inbox']))
{
$model->attributes=$_POST['Inbox'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Inbox');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Inbox('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Inbox']))
$model->attributes=$_GET['Inbox'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Inbox::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='inbox-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/inbox/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'inbox-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->textFieldGroup($model,'email',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->textFieldGroup($model,'phone',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->textAreaGroup($model,'message', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

	<?php echo $form->textFieldGroup($model,'isRead',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'isPublish',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'create_time',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'update_time',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'create_user_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'update_user_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/inbox/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'email',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'phone',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textAreaGroup($model,'message', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

		<?php echo $form->textFieldGroup($model,'isRead',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'isPublish',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'create_time',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'update_time',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'create_user_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'update_user_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/inbox/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('phone')); ?>:</b>
	<?php echo CHtml::encode($data->phone); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('message')); ?>:</b>
	<?php echo CHtml::encode($data->message); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('isRead')); ?>:</b>
	<?php echo CHtml::encode($data->isRead); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('isPublish')); ?>:</b>
	<?php echo CHtml::encode($data->isPublish); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_time')); ?>:</b>
	<?php echo CHtml::encode($data->update_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_user_id')); ?>:</b>
	<?php echo CHtml::encode($data->create_user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_user_id')); ?>:</b>
	<?php echo CHtml::encode($data->update_user_id); ?>
	<br />

	*/ ?>

</div>

protected/views/inbox/admin.php
<?php
$this->breadcrumbs=array(
	'Inboxes'=>array('index'),
	'Manage',
);

$this->pageTitle = 'Inbox';

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('inbox-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<div class="box box-parimary">
	<div class="box-body">
	<?php $this->widget('booster.widgets.TbGridView',array(
	'id'=>'inbox-grid',
	'type' =>'hover striped',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
			//'id',
			array(
				'header'=>'No',
				'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize+$row+1',
				'htmlOptions'=>array(
					'style'=>'text-align:center',
					'width'=>'30px',
				),
			),
			array(
			      'name'=>'is_read',
			      'filter'=>array('0'=>'Unread', '1'=>'Read'),
			      'header'=>'Read/Unread',
			      'type'=>'raw',
			      'value'=>'$data->is_read ==0 ? CHtml::tag("i",array("class"=>"fa fa-envelope"),"") :
					 CHtml::tag("i",array("class"=>"fa fa-envelope-o"),"") ',
					'htmlOptions'=>array(
						'style'=>'text-align:center',
						'width'=>'100px',
					),
			),
			'subjek',
			'name',
			'email',
			'phone',
			//'message',
			
			/*
			'is_publish',
			'create_time',
			'update_time',
			'create_user_id',
			'update_user_id',
			*/
	array(
		'header'=>'Pilihan',
		'class'=>'booster.widgets.TbButtonColumn',
		'template'=>'{view} {delete}',
		'htmlOptions'=>array(
					'style'=>'text-align:center',
					'width'=>'80px',
				),
	),
	),
	)); ?>
	</div>
</div>

protected/views/inbox/create.php
<?php
$this->breadcrumbs=array(
	'Inboxes'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Inbox','url'=>array('index')),
array('label'=>'Manage Inbox','url'=>array('admin')),
);
?>

<h1>Create Inbox</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/inbox/index.php
<?php
$this->breadcrumbs=array(
	'Inboxes',
);

$this->menu=array(
array('label'=>'Create Inbox','url'=>array('create')),
array('label'=>'Manage Inbox','url'=>array('admin')),
);
?>

<h1>Inboxes</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/inbox/update.php
<?php
$this->breadcrumbs=array(
	'Inboxes'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Inbox','url'=>array('index')),
	array('label'=>'Create Inbox','url'=>array('create')),
	array('label'=>'View Inbox','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Inbox','url'=>array('admin')),
	);
	?>

	<h1>Update Inbox <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/inbox/view.php
<?php
$this->breadcrumbs=array(
	'Inboxes'=>array('index'),
	$model->name,
);

$this->pageTitle='Read Inbox ';
?>

<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title"><i class="fa fa-envelope-o"></i> Visitor Message</h3>
      <div class="box-tools pull-right">
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Previous"><i class="fa fa-chevron-left"></i></a>
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Next"><i class="fa fa-chevron-right"></i></a>
      </div>
    </div><!-- /.box-header -->
    <div class="box-body no-padding">
      <div class="mailbox-read-info">
        <h3><?php echo $model->subjek;?></h3>
        <h5><b>From: </b><?php echo $model->name;?> | <b>Email:</b> <?php echo $model->email;?> | <b>Phone: </b><?php echo $model->phone;?> <span class="mailbox-read-time pull-right"><?php echo Tools::getDateTime($model->create_time);?></span></h5>
      </div><!-- /.mailbox-read-info -->
      <div class="mailbox-controls with-border">
        <div class="btn-group">
          <?php $this->widget('booster.widgets.TbButton', array(
                            'buttonType'=>'link',
                            'icon'=>'trash white',
                            'label'=>'',
                            'context'=>'default',
                            'url'=>array('inbox/delete','id'=>$model->id),
                            'htmlOptions'=>array('data-toggle'=>'tooltip', 'title'=>'Hapus', 'class'=>'btn btn-default btn-sm', 'confirm' => 'Anda yakin akan menghapus data ini?'),
            )); ?>
            <button class="btn btn-default btn-sm" data-toggle="tooltip" title="Tandai"><i class="fa fa-tag"></i></button>
            <button class="btn btn-default btn-sm" data-toggle="tooltip" title="Print"><i class="fa fa-print"></i></button>
        </div><!-- /.btn-group -->
        
      </div><!-- /.mailbox-controls -->
      <div class="mailbox-read-message">
            <?php echo $model->message;?>
      </div><!-- /.mailbox-read-message -->
    </div><!-- /.box-body -->
    <div class="box-footer">
        <?php $this->widget('booster.widgets.TbButton', array(
                    'buttonType'=>'link',
                    'htmlOptions'=>array('class'=>'btn-flat'),
                    'url'=>array('admin'),
                    'context'=>'primary',
                    'icon'=>'list white',
                    'label'=>'Inbox List',
            )); ?>
    </div><!-- /.box-footer -->
  </div><!-- /. box -->